{% set name = "hashery" %}
{% set version = "2.1.2" %}
{% set sha256 = "d239cc2310401903f6b79d458c2bbef5bf74c46f3f974ae9c1061fb74a404862" %}
{% set build = 2 %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: {{ sha256 }}

build:
  noarch: generic
  number: {{ build }}
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r hashery -e 'exit 0'

about:
  home: https://rubygems.org/gems/hashery
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Hashery is a tight collection of Hash-like classes.

  doc_url: https://www.rubydoc.info/gems/hashery
  dev_url: https://github.com/rubyworks/hashery

extra:
  recipe-maintainers:
    - ajaypnair09
    - rudispr
